name: Deploy Development test
env:
  REPO_OWNER: rafaelaraujo-ezops
  REPO_NAME: test
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  STAGE: development
  APP_NAME: ldrq-web
  AWS_REGION: ${{secrets.AWS_REGION}} 

on:
  repository_dispatch:
    types: [run-dev]
    
  push:
    branches: [ feature/pipeline ]
jobs:
  
  job:
  
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run ${{ github.event.client_payload.command }}
        run: npm run ${{ github.event.client_payload.command }} allinone


      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Git Checkout Infra
        uses: actions/checkout@v3
        with:
          repository: arqu-co/infra
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: infra
          ref: test/copy-repo


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Bucket Change Set
        id: s3-service
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: RQ-${{ env.STAGE }}-ldrq-web-s3-bucket
          template: infra/devops/service/ldrq-web/cloudformation/s3-service.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            Stage=${{ env.STAGE }},
            RepositoryName=${{env.APP_NAME}}

      - name: Create Cloudfront Change Set
        id: cloudfront-service
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: RQ-${{ env.STAGE }}-ldrq-web-cloudfront
          template: infra/devops/service/ldrq-web/cloudformation/cloudfront-service.yml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            Stage=${{ env.STAGE }},
            RepositoryName=${{env.APP_NAME}}

      - name: Build
        run: |
          npm install
          npx vue-cli-service build --mode ${{ env.STAGE }}
          aws s3 sync dist/ s3://rq-${{ env.STAGE }}-ldrq-web/
      
      - name: Invalidate
        run: CLOUDFRONT_ID=`aws ssm get-parameter --region us-west-2 --with-decryption --name /SERVICE/${{ env.STAGE }}/ldrq-web/CLOUDFRONT_ID --output text --query Parameter.Value` ; aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
