name: testim-quick-goldenpath-tests

on: [pull_request_target]

jobs:
  run-testim-goldenpath:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      STAGE: development
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        id: setupNode
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # - name: Send Slack Message - Start
      #   uses: act10ns/slack@v1
      #   with:
      #     status: starting
      #     message: Starting TestIM (https://tinyurl.com/2p8w26dv)
      #   if: always()

      - name: Run TestIM
        id: testIM
        run: npm i -g @testim/testim-cli && testim --label "${{ env.STAGE }}" --token "ZKUis2F50BZxHTyNvXaft8Uoslxc5I9Dm4WHKwh2AJbSduJVIU" --project "HTi7rU3h1uFzdCMumHzB" --grid "Testim-Grid"
        continue-on-error: true

      - name: Close PR
        uses: superbrothers/close-pull-request@v3
        if: steps.testIM.outcome != 'success'
        with:
          comment: "The test return a error"

        


      # - name: Send Slack Message - Finish
      #   uses: act10ns/slack@v1
      #   with:
      #     status: ${{ steps.testIm.outcome }}
      #     steps: ${{ toJson(steps) }}
      #     config: .github/slack.yml
      #   if: always()
